version: "1"
rules:
  - base: main
    upstream: Artificial-Pancreas:main    # change `wei` to the owner of upstream repo
    mergeMethod: hardreset
  - base: dev
    upstream: Artificial-Pancreas:dev    # change `wei` to the owner of upstream repo
    mergeMethod: hardreset
