//
//  DanaPacketType.swift
//  DanaKit
//
//  Created by Bastiaan Verhaar on 06/12/2023.
//  Copyright © 2023 Randall Knutson. All rights reserved.
//

struct DanaPacketType {
    static let TYPE_ENCRYPTION_REQUEST: UInt8 = 0x01
    static let TYPE_ENCRYPTION_RESPONSE: UInt8 = 0x02
    static let TYPE_COMMAND: UInt8 = 0xa1
    static let TYPE_RESPONSE: UInt8 = 0xb2
    static let TYPE_NOTIFY: UInt8 = 0xc3

    static let OPCODE_ENCRYPTION__PUMP_CHECK: UInt8 = 0x00
    static let OPCODE_ENCRYPTION__TIME_INFORMATION: UInt8 = 0x01
    static let OPCODE_ENCRYPTION__CHECK_PASSKEY: UInt8 = 0xd0
    static let OPCODE_ENCRYPTION__PASSKEY_REQUEST: UInt8 = 0xd1
    static let OPCODE_ENCRYPTION__PASSKEY_RETURN: UInt8 = 0xd2
    static let OPCODE_ENCRYPTION__GET_PUMP_CHECK: UInt8 = 0xf3
    static let OPCODE_ENCRYPTION__GET_EASYMENU_CHECK: UInt8 = 0xf4
    static let OPCODE_NOTIFY__DELIVERY_COMPLETE: UInt8 = 0x01
    static let OPCODE_NOTIFY__DELIVERY_RATE_DISPLAY: UInt8 = 0x02
    static let OPCODE_NOTIFY__ALARM: UInt8 = 0x03
    static let OPCODE_NOTIFY__MISSED_BOLUS_ALARM: UInt8 = 0x04
    static let OPCODE_REVIEW__INITIAL_SCREEN_INFORMATION: UInt8 = 0x02
    static let OPCODE_REVIEW__DELIVERY_STATUS: UInt8 = 0x03
    static let OPCODE_REVIEW__GET_PASSWORD: UInt8 = 0x04
    static let OPCODE_REVIEW__BOLUS_AVG: UInt8 = 0x10
    static let OPCODE_REVIEW__BOLUS: UInt8 = 0x11
    static let OPCODE_REVIEW__DAILY: UInt8 = 0x12
    static let OPCODE_REVIEW__PRIME: UInt8 = 0x13
    static let OPCODE_REVIEW__REFILL: UInt8 = 0x14
    static let OPCODE_REVIEW__BLOOD_GLUCOSE: UInt8 = 0x15
    static let OPCODE_REVIEW__CARBOHYDRATE: UInt8 = 0x16
    static let OPCODE_REVIEW__TEMPORARY: UInt8 = 0x17
    static let OPCODE_REVIEW__SUSPEND: UInt8 = 0x18
    static let OPCODE_REVIEW__ALARM: UInt8 = 0x19
    static let OPCODE_REVIEW__BASAL: UInt8 = 0x1a
    static let OPCODE_REVIEW__ALL_HISTORY: UInt8 = 0x1f
    static let OPCODE_REVIEW__GET_SHIPPING_INFORMATION: UInt8 = 0x20
    static let OPCODE_REVIEW__GET_PUMP_CHECK: UInt8 = 0x21
    static let OPCODE_REVIEW__GET_USER_TIME_CHANGE_FLAG: UInt8 = 0x22
    static let OPCODE_REVIEW__SET_USER_TIME_CHANGE_FLAG_CLEAR: UInt8 = 0x23
    static let OPCODE_REVIEW__GET_MORE_INFORMATION: UInt8 = 0x24
    static let OPCODE_REVIEW__SET_HISTORY_UPLOAD_MODE: UInt8 = 0x25
    static let OPCODE_REVIEW__GET_TODAY_DELIVERY_TOTAL: UInt8 = 0x26
    static let OPCODE_BOLUS__GET_STEP_BOLUS_INFORMATION: UInt8 = 0x40
    static let OPCODE_BOLUS__GET_EXTENDED_BOLUS_STATE: UInt8 = 0x41
    static let OPCODE_BOLUS__GET_EXTENDED_BOLUS: UInt8 = 0x42
    static let OPCODE_BOLUS__GET_DUAL_BOLUS: UInt8 = 0x43
    static let OPCODE_BOLUS__SET_STEP_BOLUS_STOP: UInt8 = 0x44
    static let OPCODE_BOLUS__GET_CARBOHYDRATE_CALCULATION_INFORMATION: UInt8 = 0x45
    static let OPCODE_BOLUS__GET_EXTENDED_MENU_OPTION_STATE: UInt8 = 0x46
    static let OPCODE_BOLUS__SET_EXTENDED_BOLUS: UInt8 = 0x47
    static let OPCODE_BOLUS__SET_DUAL_BOLUS: UInt8 = 0x48
    static let OPCODE_BOLUS__SET_EXTENDED_BOLUS_CANCEL: UInt8 = 0x49
    static let OPCODE_BOLUS__SET_STEP_BOLUS_START: UInt8 = 0x4a
    static let OPCODE_BOLUS__GET_CALCULATION_INFORMATION: UInt8 = 0x4b
    static let OPCODE_BOLUS__GET_BOLUS_RATE: UInt8 = 0x4c
    static let OPCODE_BOLUS__SET_BOLUS_RATE: UInt8 = 0x4d
    static let OPCODE_BOLUS__GET_CIR_CF_ARRAY: UInt8 = 0x4e
    static let OPCODE_BOLUS__SET_CIR_CF_ARRAY: UInt8 = 0x4f
    static let OPCODE_BOLUS__GET_BOLUS_OPTION: UInt8 = 0x50
    static let OPCODE_BOLUS__SET_BOLUS_OPTION: UInt8 = 0x51
    static let OPCODE_BOLUS__GET_24_CIR_CF_ARRAY: UInt8 = 0x52
    static let OPCODE_BOLUS__SET_24_CIR_CF_ARRAY: UInt8 = 0x53
    static let OPCODE_BASAL__SET_TEMPORARY_BASAL: UInt8 = 0x60
    static let OPCODE_BASAL__TEMPORARY_BASAL_STATE: UInt8 = 0x61
    static let OPCODE_BASAL__CANCEL_TEMPORARY_BASAL: UInt8 = 0x62
    static let OPCODE_BASAL__GET_PROFILE_NUMBER: UInt8 = 0x63
    static let OPCODE_BASAL__SET_PROFILE_NUMBER: UInt8 = 0x64
    static let OPCODE_BASAL__GET_PROFILE_BASAL_RATE: UInt8 = 0x65
    static let OPCODE_BASAL__SET_PROFILE_BASAL_RATE: UInt8 = 0x66
    static let OPCODE_BASAL__GET_BASAL_RATE: UInt8 = 0x67
    static let OPCODE_BASAL__SET_BASAL_RATE: UInt8 = 0x68
    static let OPCODE_BASAL__SET_SUSPEND_ON: UInt8 = 0x69
    static let OPCODE_BASAL__SET_SUSPEND_OFF: UInt8 = 0x6a
    static let OPCODE_OPTION__GET_PUMP_TIME: UInt8 = 0x70
    static let OPCODE_OPTION__SET_PUMP_TIME: UInt8 = 0x71
    static let OPCODE_OPTION__GET_USER_OPTION: UInt8 = 0x72
    static let OPCODE_OPTION__SET_USER_OPTION: UInt8 = 0x73
    static let OPCODE_BASAL__APS_SET_TEMPORARY_BASAL: UInt8 = 0xc1
    static let OPCODE__APS_HISTORY_EVENTS: UInt8 = 0xc2
    static let OPCODE__APS_SET_EVENT_HISTORY: UInt8 = 0xc3
    static let OPCODE_REVIEW__GET_PUMP_DEC_RATIO: UInt8 = 0x80
    static let OPCODE_GENERAL__GET_SHIPPING_VERSION: UInt8 = 0x81
    static let OPCODE_OPTION__GET_EASY_MENU_OPTION: UInt8 = 0x74
    static let OPCODE_OPTION__SET_EASY_MENU_OPTION: UInt8 = 0x75
    static let OPCODE_OPTION__GET_EASY_MENU_STATUS: UInt8 = 0x76
    static let OPCODE_OPTION__SET_EASY_MENU_STATUS: UInt8 = 0x77
    static let OPCODE_OPTION__GET_PUMP_UTC_AND_TIME_ZONE: UInt8 = 0x78
    static let OPCODE_OPTION__SET_PUMP_UTC_AND_TIME_ZONE: UInt8 = 0x79
    static let OPCODE_OPTION__GET_PUMP_TIME_ZONE: UInt8 = 0x7a
    static let OPCODE_OPTION__SET_PUMP_TIME_ZONE: UInt8 = 0x7b
    static let OPCODE_ETC__SET_HISTORY_SAVE: UInt8 = 0xe0
    static let OPCODE_ETC__KEEP_CONNECTION: UInt8 = 0xff
}
