import Foundation
import SwiftUI

struct FoodItemEditorSheet: View {
    let existingItem: FoodItemDetailed?
    let title: String
    let onSave: (FoodItemDetailed) -> Void
    let onCancel: () -> Void
    let allExistingTags: Set<String>
    let showTagsAndFavorite: Bool

    @State private var nutritionMode: NutritionEntryMode = .perServing
    @State private var servingSizeUnit: MealUnits = .grams
    @State private var editedName: String = ""
    @State private var nutrientValues: [NutrientType: Decimal] = [:]
    @State private var micronutrientValues: [MicroNutrient: Decimal] = [:]
    @State private var servingSize: Decimal? = nil
    @State private var editedTags: Set<String> = []
    @State private var showingAddNewTag = false
    @State private var newTagText: String = ""

    enum NutritionEntryMode: LocalizedStringKey, CaseIterable, Hashable {
        case perServing = "Per Serving"
        case per100g = "Per 100g"
        case per100ml = "Per 100ml"

        var nutritionType: NutritionEntryType {
            switch self {
            case .perServing:
                return .perServing
            case .per100g,
                 .per100ml:
                return .per100
            }
        }

        var unit: MealUnits {
            switch self {
            case .per100g,
                 .perServing:
                return .grams
            case .per100ml:
                return .milliliters
            }
        }
    }

    enum NutritionEntryType {
        case perServing
        case per100
    }

    private var selectedUnit: MealUnits {
        nutritionMode == .perServing ? servingSizeUnit : nutritionMode.unit
    }

    private var canSave: Bool {
        NutrientType.allCases
            .filter { $0.isPrimary }
            .allSatisfy { (nutrientValues[$0] ?? 0) >= 0 }
    }

    init(
        existingItem: FoodItemDetailed?,
        title: String? = nil,
        allExistingTags: Set<String> = [],
        showTagsAndFavorite: Bool = false,
        onSave: @escaping (FoodItemDetailed) -> Void,
        onCancel: @escaping () -> Void
    ) {
        self.existingItem = existingItem
        self.title = title ?? (existingItem != nil ? "Edit Food" : "Add Food Manually")
        self.allExistingTags = allExistingTags
        self.showTagsAndFavorite = showTagsAndFavorite
        self.onSave = onSave
        self.onCancel = onCancel

        if let item = existingItem {
            _editedName = State(initialValue: item.name)
            _editedTags = State(initialValue: Set(item.tags ?? []))

            switch item.nutrition {
            case let .per100(values, _):
                let mode: NutritionEntryMode = (item.units ?? .grams) == .milliliters ? .per100ml : .per100g
                _nutritionMode = State(initialValue: mode)
                _nutrientValues = State(initialValue: values)

                _micronutrientValues = State(
                    initialValue: Dictionary(
                        uniqueKeysWithValues: item.micronutrient.map {
                            ($0.substance, $0.amountPer100)
                        }
                    )
                )

            case let .perServing(values, _):
                _nutritionMode = State(initialValue: .perServing)
                _servingSizeUnit = State(initialValue: item.units ?? .grams)
                _nutrientValues = State(initialValue: values)

                _micronutrientValues = State(
                    initialValue: Dictionary(
                        uniqueKeysWithValues: item.micronutrient.map {
                            ($0.substance, $0.amount)
                        }
                    )
                )
            }

            if let servingSize = item.standardServingSize, servingSize > 0 {
                _servingSize = State(initialValue: servingSize)
            }
        }
    }

    private func autoGeneratedName() -> String {
        let carbs = nutrientValues[.carbs] ?? 0
        let protein = nutrientValues[.protein] ?? 0
        let fat = nutrientValues[.fat] ?? 0

        let total = carbs + protein + fat
        guard total > 0 else { return "Food" }

        let carbPercent = (carbs / total) * 100
        let proteinPercent = (protein / total) * 100
        let fatPercent = (fat / total) * 100

        if carbPercent < 10 {
            if proteinPercent > 50 { return "Lean Protein" }
            if fatPercent > 60 { return "Fatty Food" }
            return "Low-Carb Food"
        }

        if carbPercent > 50 {
            if carbPercent > 80 { return "Starchy Food" }
            return "Carb Food"
        }

        if proteinPercent > 50 {
            if fatPercent < 10 { return "Lean Protein" }
            return "Protein Food"
        }

        if fatPercent > 50 {
            return "Fatty Food"
        }

        if carbPercent > 30 && proteinPercent > 30 {
            return "Mixed Food"
        }

        return "Food"
    }

    var body: some View {
        NavigationStack {
            VStack(spacing: 0) {
                VStack(alignment: .leading, spacing: 8) {
                    Text("Food Name")
                        .font(.caption)
                        .fontWeight(.semibold)
                        .foregroundColor(.secondary)
                        .padding(.horizontal)

                    HStack(spacing: 8) {
                        DismissableTextField(
                            autoGeneratedName(),
                            text: $editedName,
                            liveEditing: true
                        )
                        .padding(8)
                        .background(Color(.systemGray3))
                        .cornerRadius(4)

                        if showTagsAndFavorite {
                            Button {
                                withAnimation(.easeInOut(duration: 0.2)) {
                                    if editedTags.contains(FoodTags.favorites) {
                                        editedTags.remove(FoodTags.favorites)
                                    } else {
                                        editedTags.insert(FoodTags.favorites)
                                    }
                                }
                            } label: {
                                Image(systemName: editedTags.contains(FoodTags.favorites) ? "star.fill" : "star")
                                    .font(.system(size: 14, weight: .medium))
                                    .foregroundColor(editedTags.contains(FoodTags.favorites) ? .white : .orange)
                                    .padding(.horizontal, 8)
                                    .padding(.vertical, 6)
                                    .background(
                                        RoundedRectangle(cornerRadius: 8, style: .continuous)
                                            .fill(
                                                editedTags.contains(FoodTags.favorites)
                                                    ? Color.orange.opacity(0.75)
                                                    : Color.orange.opacity(0.08)
                                            )
                                    )
                                    .overlay(
                                        RoundedRectangle(cornerRadius: 8, style: .continuous)
                                            .strokeBorder(
                                                editedTags.contains(FoodTags.favorites)
                                                    ? Color.clear
                                                    : Color.orange.opacity(0.35),
                                                lineWidth: 1
                                            )
                                    )
                            }
                            .buttonStyle(.plain)
                        }
                    }
                    .padding(.horizontal)
                }
                .padding(.top, 8)
                .padding(.bottom, 12)

                VStack(spacing: 12) {
                    Picker("Nutrition Type", selection: $nutritionMode) {
                        ForEach(NutritionEntryMode.allCases, id: \.self) { mode in
                            Text(mode.rawValue).tag(mode)
                        }
                    }
                    .pickerStyle(.segmented)
                    .padding(.horizontal)
                    .padding(.top, 16)
                    .onChange(of: nutritionMode) { oldMode, newMode in
                        handleNutritionModeChange(from: oldMode, to: newMode)
                    }
                }

                FoodItemNutritionEditor(
                    nutritionMode: $nutritionMode,
                    servingSizeUnit: $servingSizeUnit,
                    nutrientValues: $nutrientValues,
                    micronutrientValues: $micronutrientValues,
                    servingSize: $servingSize
                )

                if showTagsAndFavorite {
                    CollapsibleTagsSection(
                        selectedTags: $editedTags,
                        allExistingTags: allExistingTags,
                        showingAddNewTag: $showingAddNewTag
                    )
                    .padding(.horizontal)
                    .padding(.top, 12)
                    .padding(.bottom, 8)
                }

                HStack(spacing: 12) {
                    Button("Cancel") {
                        onCancel()
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 12)
                    .background(Color.gray.opacity(0.2))
                    .foregroundColor(.primary)
                    .cornerRadius(10)

                    Button("Save") {
                        saveFoodItem()
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 12)
                    .background(canSave ? Color.accentColor : Color.gray.opacity(0.2))
                    .foregroundColor(canSave ? .white : .secondary)
                    .cornerRadius(10)
                    .disabled(!canSave)
                }
                .padding(.horizontal)
                .padding(.vertical, 16)
                .background(Color(.systemBackground))
            }
            .navigationTitle(NSLocalizedString(title, comment: "Title"))
            .navigationBarTitleDisplayMode(.inline)
        }
        .background(Color(.systemGroupedBackground))
        .alert("Add New Tag", isPresented: $showingAddNewTag) {
            TextField("Tag name", text: $newTagText)
                .autocapitalization(.none)

            Button("Cancel", role: .cancel) {
                newTagText = ""
            }

            Button("Add") {
                let trimmed = newTagText.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
                if !trimmed.isEmpty, trimmed != FoodTags.favorites {
                    editedTags.insert(trimmed)
                }
                newTagText = ""
            }
        } message: {
            Text("Enter a tag name (e.g., breakfast, snack, low-carb)")
        }
    }

    private func handleNutritionModeChange(from oldMode: NutritionEntryMode, to newMode: NutritionEntryMode) {
        guard oldMode.nutritionType != newMode.nutritionType else { return }

        switch (oldMode.nutritionType, newMode.nutritionType) {
        case (.per100, .perServing):
            if let servingSize, servingSize > 0 {
                let scaleFactor = servingSize / 100

                for nutrient in NutrientType.allCases {
                    if let value = nutrientValues[nutrient] {
                        nutrientValues[nutrient] = round(value * scaleFactor, to: 1)
                    }
                }

                for micro in MicroNutrient.allCases {
                    if let value = micronutrientValues[micro] {
                        micronutrientValues[micro] = round(value * scaleFactor, to: 3)
                    }
                }
            }

            switch oldMode {
            case .per100g:
                servingSizeUnit = .grams
            case .per100ml:
                servingSizeUnit = .milliliters
            default:
                break
            }

        case (.perServing, .per100):
            if let servingSize, servingSize > 0 {
                let scaleFactor = 100 / servingSize

                for nutrient in NutrientType.allCases {
                    if let value = nutrientValues[nutrient] {
                        nutrientValues[nutrient] = round(value * scaleFactor, to: 1)
                    }
                }

                for micro in MicroNutrient.allCases {
                    if let value = micronutrientValues[micro] {
                        micronutrientValues[micro] = round(value * scaleFactor, to: 3)
                    }
                }
            }

        default:
            break
        }
    }

    private func round(_ value: Decimal, to places: Int) -> Decimal {
        var rounded = value
        var result = Decimal()
        NSDecimalRound(&result, &rounded, places, .plain)
        return result
    }

    private func saveFoodItem() {
        let finalName = editedName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            ? autoGeneratedName()
            : editedName

        var nutrientValuesCopy: [NutrientType: Decimal] = [:]

        for nutrient in NutrientType.allCases {
            if let value = nutrientValues[nutrient] {
                nutrientValuesCopy[nutrient] = value
            } else if nutrient.isPrimary {
                nutrientValuesCopy[nutrient] = 0
            }
        }

        let standardServingSize: Decimal? = {
            guard let value = servingSize, value > 0 else { return nil }
            return value
        }()

        let tagsArray: [String]? = {
            guard !editedTags.isEmpty else { return nil }

            var result = Array(editedTags)
            result.sort { tag1, tag2 in
                if tag1 == FoodTags.favorites { return true }
                if tag2 == FoodTags.favorites { return false }
                return tag1 < tag2
            }

            return result
        }()

        let nutrition: FoodNutrition = switch nutritionMode.nutritionType {
        case .per100:
            .per100(values: nutrientValuesCopy, portionSize: standardServingSize ?? 100)

        case .perServing:
            .perServing(values: nutrientValuesCopy, servingsMultiplier: 1)
        }

        let finalMicronutrients: [MicronutrientValue] = micronutrientValues
            .filter { $0.value > 0 }
            .map { nutrient, amount in
                let amountPer100: Decimal

                switch nutritionMode.nutritionType {
                case .per100:
                    amountPer100 = amount

                case .perServing:
                    if let standardServingSize, standardServingSize > 0 {
                        amountPer100 = amount / standardServingSize * 100
                    } else {
                        amountPer100 = amount
                    }
                }

                return MicronutrientValue(
                    substance: nutrient,
                    amount: amount,
                    amountPer100: amountPer100
                )
            }
            .sorted { $0.name < $1.name }

        let foodItem: FoodItemDetailed

        if let existingItem {
            foodItem = existingItem.copy(
                name: finalName,
                nutrition: nutrition,
                micronutrient: finalMicronutrients,
                standardServingSize: standardServingSize,
                units: selectedUnit,
                tags: tagsArray
            )
        } else {
            foodItem = FoodItemDetailed(
                name: finalName,
                nutrition: nutrition,
                micronutrient: finalMicronutrients,
                standardServingSize: standardServingSize,
                units: selectedUnit,
                tags: tagsArray,
                source: .manual
            )
        }

        onSave(foodItem)
    }
}

private struct FoodItemNutritionEditor: View {
    @Binding var nutritionMode: FoodItemEditorSheet.NutritionEntryMode
    @Binding var servingSizeUnit: MealUnits
    @Binding var nutrientValues: [NutrientType: Decimal]
    @Binding var micronutrientValues: [MicroNutrient: Decimal]
    @Binding var servingSize: Decimal?

    @State private var showAllNutrients: Bool = false

    init(
        nutritionMode: Binding<FoodItemEditorSheet.NutritionEntryMode>,
        servingSizeUnit: Binding<MealUnits>,
        nutrientValues: Binding<[NutrientType: Decimal]>,
        micronutrientValues: Binding<[MicroNutrient: Decimal]>,
        servingSize: Binding<Decimal?>
    ) {
        _nutritionMode = nutritionMode
        _servingSizeUnit = servingSizeUnit
        _nutrientValues = nutrientValues
        _micronutrientValues = micronutrientValues
        _servingSize = servingSize

        let hasOptionalNutrients = NutrientType.allCases.contains {
            !$0.isPrimary && (nutrientValues.wrappedValue[$0] ?? 0) > 0
        }

        let hasMicronutrients = MicroNutrient.allCases.contains {
            (micronutrientValues.wrappedValue[$0] ?? 0) > 0
        }

        _showAllNutrients = State(initialValue: hasOptionalNutrients || hasMicronutrients)
    }

    private var nutritionType: FoodItemEditorSheet.NutritionEntryType {
        nutritionMode.nutritionType
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                VStack(spacing: 8) {
                    ForEach(NutrientType.allCases.filter { $0.isPrimary }) { nutrient in
                        FoodItemNutritionRow(
                            localizedLabel: nutrient.localizedLabel,
                            value: Binding(
                                get: { nutrientValues[nutrient] },
                                set: { updated in
                                    if let updated {
                                        nutrientValues[nutrient] = updated
                                    } else {
                                        nutrientValues.removeValue(forKey: nutrient)
                                    }
                                }
                            ),
                            unit: nutrient.unit
                        )

                        Divider()
                    }

                    FoodItemCaloriesDisplayRow(
                        baseCalories: nutrientValues.calories
                    )

                    // Fiber, Sugar, Vitamins and minerals
                    if showAllNutrients {
                        ForEach(NutrientType.allCases.filter { !$0.isPrimary }) { nutrient in
                            Divider()

                            FoodItemNutritionRow(
                                localizedLabel: nutrient.localizedLabel,
                                value: Binding(
                                    get: { nutrientValues[nutrient] ?? 0 },
                                    set: { updated in
                                        if let updated, updated > 0 {
                                            nutrientValues[nutrient] = updated
                                        } else {
                                            nutrientValues.removeValue(forKey: nutrient)
                                        }
                                    }
                                ),
                                unit: nutrient.unit
                            )
                        }

                        Divider()

                        Text("Micronutrients")
                            .font(.caption)
                            .fontWeight(.semibold)
                            .foregroundColor(.secondary)
                            .padding(.leading, 12)
                            .padding(.top, 8)

                        ForEach(MicroNutrient.allCases) { micronutrient in
                            Divider()

                            FoodItemNutritionRow(
                                localizedLabel: micronutrient.displayName,
                                value: Binding(
                                    get: { micronutrientValues[micronutrient] ?? 0 },
                                    set: { updated in
                                        if let updated, updated > 0 {
                                            micronutrientValues[micronutrient] = updated
                                        } else {
                                            micronutrientValues.removeValue(forKey: micronutrient)
                                        }
                                    }
                                ),
                                unit: micronutrient.dimension
                            )
                        }

                        Divider()
                    }

                    if !showAllNutrients {
                        Button {
                            withAnimation(.easeInOut(duration: 0.2)) {
                                showAllNutrients = true
                            }
                        } label: {
                            HStack {
                                Image(systemName: "chevron.down")
                                    .font(.caption)
                                    .foregroundColor(.secondary)

                                Text("Show All Nutrients")
                                    .font(.caption)
                                    .foregroundColor(.secondary)
                            }
                            .padding(.vertical, 8)
                            .frame(maxWidth: .infinity)
                        }
                        .buttonStyle(.plain)
                    }

                    FoodItemServingSizeRow(
                        value: $servingSize,
                        unit: nutritionMode == .perServing ? $servingSizeUnit : .constant(nutritionMode.unit),
                        allowToggle: nutritionMode == .perServing
                    )
                }
                .padding(12)
                .background(
                    RoundedRectangle(cornerRadius: 12, style: .continuous)
                        .fill(Color(.secondarySystemBackground))
                )
                .padding(.horizontal)

                Spacer(minLength: 8)
            }
            .padding(.vertical)
        }
        .scrollDismissesKeyboard(.immediately)
    }
}

private struct FoodItemNutritionRow: View {
    let localizedLabel: String
    @Binding var value: Decimal?
    let unit: Dimension

    private static let nutritionValueFormatter: NumberFormatter = {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.maximumFractionDigits = 3
        formatter.minimumFractionDigits = 0
        formatter.usesGroupingSeparator = false
        return formatter
    }()

    var body: some View {
        HStack(spacing: 8) {
            Text(localizedLabel)
                .font(.subheadline)
                .foregroundColor(.primary.opacity(0.8))
                .frame(maxWidth: .infinity, alignment: .leading)

            HStack(spacing: 4) {
                OptionalDecimalTextField(
                    "0",
                    value: $value,
                    formatter: Self.nutritionValueFormatter,
                    liveEditing: true
                )
                .foregroundColor(.secondary)
                .padding(8)
                .background(Color(.systemGray4))
                .cornerRadius(4)

                Text(unit.symbol)
                    .font(.caption2)
                    .foregroundColor(.secondary.opacity(0.7))
                    .frame(width: 28, alignment: .leading)
            }
            .frame(width: 100, alignment: .trailing)
        }
        .padding(.leading, 12)
        .padding(.trailing, 6)
        .padding(.vertical, 6)
    }
}

private struct FoodItemCaloriesDisplayRow: View {
    let baseCalories: Decimal

    var body: some View {
        HStack(spacing: 8) {
            HStack(spacing: 4) {
                Text(NSLocalizedString("Calories", comment: ""))
                    .font(.subheadline)
                    .foregroundColor(.primary.opacity(0.8))

                Image(systemName: "function")
                    .font(.system(size: 11))
                    .foregroundColor(.blue.opacity(0.8))
            }
            .frame(maxWidth: .infinity, alignment: .leading)

            HStack(spacing: 2) {
                Text("\(Int(truncating: baseCalories as NSNumber))")
                    .font(.subheadline)
                    .foregroundColor(.secondary)

                Text(UnitEnergy.kilocalories.symbol)
                    .font(.caption2)
                    .foregroundColor(.secondary.opacity(0.7))
                    .frame(width: 28, alignment: .leading)
            }
            .frame(width: 100, alignment: .trailing)
        }
        .padding(.leading, 12)
        .padding(.trailing, 6)
        .padding(.vertical, 6)
    }
}

private struct FoodItemServingSizeRow: View {
    @Binding var value: Decimal?
    @Binding var unit: MealUnits
    let allowToggle: Bool

    private static let servingSizeFormatter: NumberFormatter = {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.maximumFractionDigits = 1
        formatter.minimumFractionDigits = 0
        formatter.usesGroupingSeparator = false
        return formatter
    }()

    private var servingSizeField: some View {
        HStack(spacing: 4) {
            OptionalDecimalTextField(
                "",
                value: $value,
                formatter: Self.servingSizeFormatter,
                liveEditing: true
            )
            .foregroundColor(.secondary)
            .padding(8)
            .background(Color(.systemGray4))
            .cornerRadius(4)

            Text(unit.dimension.symbol)
                .font(.caption2)
                .foregroundColor(.secondary.opacity(0.7))
                .frame(width: 28, alignment: .leading)
        }
        .frame(width: 100, alignment: .trailing)
    }

    private var servingSizeFieldLabel: some View {
        Text("Standard Serving")
            .font(.subheadline)
            .foregroundColor(.primary.opacity(0.8))
            .frame(maxWidth: .infinity, alignment: .leading)
    }

    private var unitSelector: some View {
        HStack(spacing: 0) {
            ForEach([MealUnits.grams, MealUnits.milliliters], id: \.self) { option in
                Button {
                    unit = option
                } label: {
                    Text(option.dimension.symbol)
                        .font(.footnote)
                        .fontWeight(.semibold)
                        .foregroundColor(unit == option ? .white : .secondary)
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 5)
                        .background(
                            RoundedRectangle(cornerRadius: 6, style: .continuous)
                                .fill(unit == option ? Color.accentColor : Color.clear)
                        )
                }
                .buttonStyle(.plain)
            }
        }
        .frame(width: 100, alignment: .leading)
    }

    var body: some View {
        if allowToggle {
            VStack {
                servingSizeFieldLabel

                HStack(spacing: 8) {
                    unitSelector
                    Spacer()
                    servingSizeField
                }
            }
            .padding(.leading, 12)
            .padding(.trailing, 6)
            .padding(.vertical, 6)
        } else {
            HStack(spacing: 8) {
                servingSizeFieldLabel
                servingSizeField
            }
            .padding(.leading, 12)
            .padding(.trailing, 6)
            .padding(.vertical, 6)
        }
    }
}
